### ISSUE TITLE
Sqlite spatialite seems to be able to map only towards a Geometry but not the rest of the types

### ISSUE THREAD

**Issue by janagn** [borisdj/EFCore.BulkExtensions#1203]
Hi, I am getting the following exception using Sqlite spatialite module:

System.InvalidOperationException: 'No mapping exists from object type NetTopologySuite.Geometries.LineString to a known managed provider native type.'

If I don't use the EFCore.BulkExtension the add and savechanges is working as expected. Using BulkInsert I am getting the above exception. Is the implementation missing or is there any work around to add a mapping for LineStrings and Points?

Thank you

**Comment by janagn** [comment]
Hey thanks for this, see this psaudocode that follows till I make something more:
Context declarations:
```
modelBuilder.Entity<VesselTrack>(builder => {
                builder.Property(e => e.ID).ValueGeneratedNever();
                builder.HasKey(k => k.ID);
                builder.HasIndex(i => i.Day1);
                builder.HasIndex(i => new { i.RadarOrAIS, i.MMSI, i.Day1 } );
                builder.HasIndex(i => new { i.RadarOrAIS, i.TargetNo, i.Day1 });
                builder.HasIndex(i => new { i.MMSI, i.TrackID });
                builder.HasIndex(i => new { i.TargetNo, i.TrackID });
                builder.Property(c => c.Geometry2).HasSrid(4326);                
            });  
```
Entity (I have it as a string and a LineString):
```
public class VesselTrack
    {       
        ...

        public string Geometry { get; set; }         
        public LineString Geometry2 { get; set; }
    }
``` 

Service Module with work around
```
public void PopulateVesselTracksTable(DbContextOptions contextOptions, string jobName, string trackArray)
        {
            using (var plineReader = TabFileReader.Open(_hostingEnvironment.ContentRootPath +
                        Path.DirectorySeparatorChar + jobName + Path.DirectorySeparatorChar + trackArray))
            {                                  
                using (var context = new EncountersDb(contextOptions))
                {
                    int deleted = context.Set<FilteredData>().AsNoTracking().BatchDelete();
                    _logger.LogTrace("Deleted {0} rows from Filtered data table ", deleted);
                    deleted = context.Set<VesselTrack>().AsNoTracking().BatchDelete();
                    _logger.LogTrace("Deleted {0} rows from VesselTrack data table ", deleted);
                    Status = "Caching Vessel Tracks";
                    int totalFeatures = plineReader.Count;
                    int count = 0;
                    IList<VesselTrack> filteredData = new List<VesselTrack>();
                    foreach (var aTrack in plineReader.Features)
                    {
                        filteredData.Add(VesselTrack.CreateVesselTrack(aTrack));
                        if (filteredData.Count > 10000)
                        {                            
                            context.BulkInsert(filteredData);
                            filteredData.Clear();
                        }

                        ProgressPerCent = 100 * count++ / totalFeatures;                        
                    }
                    context.BulkInsert<VesselTrack>(filteredData, new BulkConfig() { SRID = 4326 });                                                           
                    filteredData.Clear();
                    int updateGeometries = context.Database.ExecuteSql($"update VesselTracks set Geometry2 = ST_GeomFromText(Geometry, 4326)");
                    _logger.LogTrace("Updated {0} Geometries in VesselTrack table", updateGeometries);                    
                    ProgressPerCent = 100;
                }
            }
        }
```

I let the property Geometry2  to be null settting only the string of the Geometry via my object and then I run at the end the 
update to work around. This way it works but I have this extra step that puts delay in the process
``` int updateGeometries = context.Database.ExecuteSql($"update VesselTracks set Geometry2 = ST_GeomFromText(Geometry, 4326)");```

If however I I construct my LineString form the begging then when it reaches the
``` context.BulkInsert<VesselTrack>(filteredData, new BulkConfig() { SRID = 4326 });  ```

I get the exception System.InvalidOperationException: 'No mapping exists from object type NetTopologySuite.Geometries.LineString to a known managed provider native type.'

**Comment by borisdj** [comment]
Fixed with latest commit, new nuget will be published till end of next week,

**Comment by janagn** [comment]
Hi, I still have the same issue with the LineString and Points in SQLite when bulk inserting. Getting the error I reported earlier this month about not being able to map LineString (and Points) to any know Geomerty type. Has the changes you put being through this 7.1.5 version nuget or are they still pending?

Thank you

**Comment by borisdj** [comment]
No fix, was was not in that version, it will be in 7.1.6 that will be published in a few days.
