### ISSUE TITLE
Connection being closed when `CalculateStats` set to true

### ISSUE THREAD

**Issue by vermilion** [borisdj/EFCore.BulkExtensions#1583]
Tested on Postgres 

Found strange behavoir when turning on `CalculateStats`. After Bulk-method being run database connection became closed

After some digging found potential cause in method `GetStatsNumbersPGAsync`. It closes connection on every call even if it was opened **Explicitly**

**Comment by borisdj** [comment]
Hi, can you write entire code snipped where the issue would be reproducible, or write a test for this.

**Comment by vermilion** [comment]
```
        var c1 = new BulkConfig { CalculateStats = true };
        var c2 = new BulkConfig { CalculateStats = true };

        await _dbContext.BulkInsertOrUpdateAsync(importData.Objects, c1);

        // connection is closed here. Next calls to BulkInsertOrUpdateAsync will fail due to closed db connection

        await _dbContext.BulkInsertOrUpdateAsync(importData.History, c2); // <-- fails
```

Here you can find stacktrace
```
System.InvalidOperationException: Connection is not open
   at Npgsql.ThrowHelper.ThrowInvalidOperationException(String message)
   at Npgsql.NpgsqlConnection.CheckReady()
   at Npgsql.NpgsqlConnection.BeginTransaction(Boolean async, IsolationLevel level, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level)
   at Npgsql.NpgsqlConnection.BeginTransaction()
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.GetStatsNumbersPGAsync(DbContext context, TableInfo tableInfo, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.GetStatsNumbersPGAsync(DbContext context, TableInfo tableInfo, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
Yes, that seems to be a bug.
Closing segment is removed from _GetStatsNumbersPGAsync_ so should be fixed now.
Change is committed and it will be published with next nuget.

**Comment by maacpiash** [comment]
Hi, I'm still facing this issue. I'm using version `9.0.1` on PostgreSQL database.
