### ISSUE TITLE
No chance to configure BulkInsert for use with HasNoKey entities

### ISSUE THREAD

**Issue by guffy1234** [borisdj/EFCore.BulkExtensions#291]
hi

The config has properties BulkConfig.PropertiesToInclude and BulkConfig.UpdateByProperties and it looks like with these properties it's possible to insert data to a table without a primary key. Unfortunately, the method
`public void LoadData<T>(DbContext context, IList<T> entities, bool loadOnlyPKColumn)`
crashes at line
`var primaryKeys = entityType.FindPrimaryKey().Properties.Select(a => a.Name).ToList();`

So I think it's would be nice to rearrange the code:
```
  var primaryKeys = entityType.FindPrimaryKey().Properties.Select(a => a.Name).ToList();
  HasSinglePrimaryKey = primaryKeys.Count == 1;
  PrimaryKeys = AreSpecifiedUpdateByProperties ? BulkConfig.UpdateByProperties : primaryKeys;
```
to support the case. 

Honestly, it would be nice if EFCore.BulkExtensions will support entities with HasNoKey for all eligible operations.

**Comment by borisdj** [comment]
Needed changes:
```C#
var primaryKeys = entityType.FindPrimaryKey()?.Properties?.Select(a => a.Name)?.ToList();
```
Also
```C#
UpdateByPropertiesAreNullable = properties.Any(a => PrimaryKeys != null && PrimaryKeys.Contains(a.Name) && a.IsNullable);
```

**Comment by awajan** [comment]
I am facing the same issue, and receiving null reference exception, obviously because there is no primary key for keyless entities. I would appreciate help on this. thanks

**Comment by gandhis1** [comment]
Just want to add another voice of support for this feature. Oh how I wish I could guarantee uniqueness on my clustered index, but data quality sucks.

**Comment by borisdj** [comment]
Fixed with Nuget 3.1.2

**Comment by gandhis1** [comment]
I'm supposed to be able to BulkInsert on `HasNoKey()` entities right? I just tested it out, confirmed I am on 3.1.2, and it is still not working for me. Here is the stack trace:

```

---> System.InvalidOperationException: EntitySet for Type: X must contain a Primary Key
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertAsync[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```

 For what it's worth, looks like @stevekirks made a change recently to add an explicit check in e747a66.

**Comment by stevekirks** [comment]
@gandhis1 I wasnt aware of this issue. My change was giving advice to the user that it wasnt supported but if entities with No Primary Key has been handled then my change should be reverted.

**Comment by borisdj** [comment]
Exception removed with 3.1.3

**Comment by gandhis1** [comment]
Now I get a null reference exception, which was the original behavior. Do I need `UpdateByProperties` or some special bulk config? Ideally that wouldn't be the case, I ought to be able to insert arbitrary records, regardless of the presence of a uniquely-identifying key.

I finally downloaded the source, debugging it at the moment to pinpoint what the issue is...
