### ISSUE TITLE
BulkInsert fails with SetOutputIdentity on Sqlite with long type

### ISSUE THREAD

**Issue by bjaminp** [borisdj/EFCore.BulkExtensions#295]
EF Core 3.1.2
EFCore.BulkExtensions 3.1.0

I am using sqlite with EFCore.

When using the following bulk insert I get an error.
```
var bulkConfig = new BulkConfig {PreserveInsertOrder = true, SetOutputIdentity = true};
this.BulkInsert(parts, bulkConfig);
```
My identity field is a long type.

Error:
`Unable to cast object of type 'System.Int32' to type 'System.Int64'.`
```
   at FastMember_dynamic.Part_1.set_Item(Object , String , Object )
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
```

**Comment by borisdj** [comment]
Fixed with 3.1.1

**Comment by Numpsy** [comment]
I think I just fell over this issue in 3.1.1 when using async bulk inserts.
Looking at the code, it looks like it might have been fixed in the Merge function, but not the MergeAsync function?

**Comment by JasonLandbridge** [comment]
This is unfortunately still an issue. If I have the following

```
var bulkConfig = new BulkConfig {PreserveInsertOrder = true, SetOutputIdentity = true};
await this.BulkInsertAsync(parts, bulkConfig, cancellationToken);
```
I get the following exception
```
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
   at lambda_method(Closure , Object , Object )
   at EFCore.BulkExtensions.FastProperty.Set(Object instance, Object value)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, 
```

In my case there is a property, which is not the Id, that is a long and contains the value: 18847646876

If I do the non-async `BulkInsert` then it works as expected.

**Comment by JasonLandbridge** [comment]
I also just noticed that the long value is not stored in the database, so the long value is ignored and it defaults to 0
