### ISSUE TITLE
MultiplePropertyListSetException after upgrading to v4.0.0 or higher

### ISSUE THREAD

**Issue by aserrabi** [borisdj/EFCore.BulkExtensions#521]
Hi,

There's a bug when adding the properties to include in v4.0.0 or higher.

This same code is working with previous versions, as you can see, the BulkConfig doesn't contain the PropertiesToExclude definition.

```
 context.BulkUpdateAsync(
        entities,
        new BulkConfig { PropertiesToInclude = propertiesToInclude })
```

Exception message: 
MultiplePropertyListSetException: Only one group of properties, either PropertiesToInclude or PropertiesToExclude can be specified, specifying both not allowed.

Thanks

**Comment by borisdj** [comment]
There is no version 4, are you referring to v5?
In EFCoreBulkTest there is example with this usage and it passes successfully, take a look there or make complete code snippet for test where the issue would be reproducible.
Also I assume you are using SqlServer.

**Comment by aserrabi** [comment]
Sorry it's after version 3.4.0, it stopped working with the current code I have.

Which is this one:
` context.BulkUpdateAsync(
        entities,
        new BulkConfig { PropertiesToInclude = propertiesToInclude })`

I'm not adding propertiesToExclude, so I don't understand why it's throwing that exception.

**Comment by sumonem** [comment]
I have same issue, strange fact is that it doesn't occur every time. It looks like it is related with data somehow. I have 3 processes which shares same code for bulk insert and update, 2 of them started failing after update and 1 still works fine.

**Comment by sumonem** [comment]
![image](https://user-images.githubusercontent.com/2345814/115005436-248f5680-9ea8-11eb-9bfc-3eeaca6b3272.png)

This is the issue. Since this change any property with default value in SQL will be included into properties to exclude, even if you defined properties to include. In such case the exception will be thrown.

**Comment by aserrabi** [comment]
It looks it was introduced in this commit: 

https://github.com/borisdj/EFCore.BulkExtensions/commit/1a9196871aded948527f8b58b96ee047cd622c7f#diff-a8eab425ec44046645a8112da55eaa9e082d8c13af26344337674e8c3dcf7691

**Comment by borisdj** [comment]
Should be fixed with v5.0.8
@sumonem thx for debug info.

**Comment by aserrabi** [comment]
Thanks a lot @borisdj and @sumonem !!

**Comment by havlikk** [comment]
It looks the bug still remains in the EFCore3.1 branch (v3.6.1). [TableInfo.cs](https://github.com/borisdj/EFCore.BulkExtensions/blob/EFCore3.1/EFCore.BulkExtensions/TableInfo.cs)
![image](https://user-images.githubusercontent.com/85875715/121880836-c5ff2100-cd0e-11eb-9411-446a1d2f1d59.png)
@borisdj Is the EFCore3.1 branch still being maintained?

**Comment by borisdj** [comment]
Not actively.
