### ISSUE TITLE
Need the entities to be sorted when using BulkInsertOrUpdate with SetOutputIdentity = true

### ISSUE THREAD

**Issue by huer12** [borisdj/EFCore.BulkExtensions#541]
I have written a little test project and the only way I get the primary key set correctly is if I order the entities by Id, first the existing Ids and then the ones which will be created. So this works:
`var itemsToInsert = entities.Where(e => e.Id != 0).OrderBy(e => e.Id).ToList();
itemsToInsert.AddRange(entities.Where(e => e.Id == 0));
await dbContext.BulkInsertOrUpdateAsync(itemsToInsert ,...`

Is that really the way to do it or is there a bug?

I'm currently using this bulk config
` private static readonly BulkConfig DefaultBulkConfig = new BulkConfig
        {
            UseTempDB = true,
            UniqueTableNameTempDb = false,
            SetOutputIdentity = true,
            PreserveInsertOrder = true,
            OmitClauseExistsExcept = true
        };`

**Comment by borisdj** [comment]
It should work regardless, can you write entire test example for reproducing the issue.

**Comment by huer12** [comment]
The attached test project has a method ValidateUpdate which validates whether the ids are the same after the bulk update and throws an Exception if this is not the case. This happens the second time you run the application, as soon as some rows already exist in the DB.
Before running the app you need to create the Db and change the connection string in the class BulkTestDbContext
 
[BulkTest.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/6394251/BulkTest.zip)

**Comment by borisdj** [comment]
Fixed with v5.1.3

**Comment by huer12** [comment]
It still does not work with InsertOrUpdate
Example: Provided Entitiy Ids:  (zero for the ones being inserted, 1 and 2 are existing)
1,0,0,2
The method CheckToSetIdentityForPreserveOrder makes that:
1,-4,-3,2
after reading the output table the output table will have this entitiesWithOutputIdentity: 
1,2,3,4

now the UpdateEntitiesIdentity is iterating in a for loop and makes this:
1 = 1
-4 = 2
-3 = 3
2 = 4

To fix that one possibility would be to sort the entites accordingly in the method UpdateEntitiesIdentity 
1. all existing ids
2. all new ids in the correct order

Another option would be to change the readme and inform that this combination does not work, that the user needs to sort the entity list theme self

**Comment by borisdj** [comment]
Try now v5.1.4

**Comment by huer12** [comment]
Thanks for the update, but unfortunately there is still an issue. In the method UpdateEntitiesIdentity() all key are set, not only the ones of the inserted entities. Because of that, the key of the updated entities is overridden and because the updated entities are not sorted, they key is set incorrectly (and the timestamp and other properties to load too)

So in the method CheckToSetIdentityForPreserveOrder() the entitiesExisting must be sorted by the PK.

Another question: 
In the method UpdateEntitiesIdentity you have the case ` else if (BulkConfig.IncludeGraph)`. If you set the bulk config to IncludeGraph = true and PreserveInsertOrder = true it will always take the first case not the IncludeGraph case. 
In my opinion you should merge these two cases to ` if (BulkConfig.PreserveInsertOrder || BulkConfig.IncludeGraph)` 

Regards

**Comment by borisdj** [comment]
Added v5.1.5

**Comment by borisdj** [comment]
PS nice notice about IncludeGraph, it is now inside PreserveInsertOrder block, since IncludeGraph has always set SetOutputIdentity and that requires PreserveInsertOrder.

**Comment by huer12** [comment]
The InsertUpdate now works. Thanks a lot!

Regarding the IncludeGraph:
The if case `if (BulkConfig.IncludeGraph)` can be completely deleted in my opinion as the PK is already set on line 753:
` if (identityPropertyName != null)
                    {
                        var identityPropertyValue = FastPropertyDict[identityPropertyName].Get(entitiesWithOutputIdentity[i]);
                        FastPropertyDict[identityPropertyName].Set(entities[i], identityPropertyValue);
                    }`

So this is doing the same and can be removed (or do I overlook something?)
`if (context.Entry(originalEntity).IsKeySet == false)
                        {
                            var newPk = context.Entry(outputEntity).Property(identityPropertyName).CurrentValue;
                            context.Entry(originalEntity).Property(identityPropertyName).CurrentValue = newPk;
                        }`

The only difference is, that in the bulk section you check whether the PK is already set. So one possibility would be to do that on line 753

`if (identityPropertyName != null && context.Entry(originalEntity).IsKeySet == false)`

But the check IsKeySet is not the fastest, to always set the same value again, as it is done now, is much faster

And another minor thing: If the loop `for (int i = 0; i < NumberOfEntities; i++)` is done like this `for (int i = 0; i < entitiesWithOutputIdentity.Count; i++)`, then this check can be deleted `if (i == entitiesWithOutputIdentity.Count) break;`

**Comment by borisdj** [comment]
Done some refactoring in this regard.
