### ISSUE TITLE
BulkInsertOrUpdateOrDelete: bulkConfig.StatsInfo.StatsNumberInserted is wrong if nothing was updated

### ISSUE THREAD

**Issue by michull** [borisdj/EFCore.BulkExtensions#666]
I'm using EFCore.BulkExtensions v6.0.7 and initialize my table on a MS SQL server with
```
context.Students.BatchDelete();
context.Students.Add(new Student() { StudentId = 1, Name = "John Doe" });
context.SaveChanges();
```

Later I'm using the following code to sync the data (in fact there is no difference):
```
List<Student> students = new() { new Student() { StudentId = 1, Name = "John Doe" }};
BulkConfig bulkConfig = new() { CalculateStats = true };
context.BulkInsertOrUpdateOrDelete(students, bulkConfig);
```

I would expect that all statistic numbers are 0, but the lines
```
Console.WriteLine($"Deleted={bulkConfig.StatsInfo.StatsNumberDeleted}");
Console.WriteLine($"Inserted={bulkConfig.StatsInfo.StatsNumberInserted}");
Console.WriteLine($"Updated={bulkConfig.StatsInfo.StatsNumberUpdated}");
```
output
```
Deleted=0
Inserted=1
Updated=0
```

The generated merge statement was as follows
```
MERGE [dbo].[Students] WITH (HOLDLOCK) AS T
USING (SELECT TOP 1 * FROM [dbo].[StudentsTemp9c324527] ORDER BY [StudentId]) AS S 
ON T.[StudentId] = S.[StudentId] 
WHEN NOT MATCHED BY TARGET THEN INSERT ([Name]) VALUES (S.[Name]) 
WHEN MATCHED AND EXISTS (SELECT S.[Name] EXCEPT SELECT T.[Name]) THEN UPDATE SET T.[Name] = S.[Name] 
WHEN NOT MATCHED BY SOURCE THEN DELETE 
OUTPUT COALESCE(INSERTED.[StudentId], DELETED.[StudentId]), COALESCE(INSERTED.[Name], DELETED.[Name]),(CASE $action WHEN 'UPDATE' THEN 1 Else 0 END),(CASE $action WHEN 'DELETE' THEN 1 Else 0 END) INTO [dbo].[StudentsTemp9c324527Output];
```

the class [TableInfo](https://github.com/borisdj/EFCore.BulkExtensions/blob/068e59d7af39f7377d7e1376a0ad15a11e528b2f/EFCore.BulkExtensions/TableInfo.cs) has the following lines:
```
int totalNumber = entities.Count;
int numberUpdated = [...]
int numberDeleted = [...]
BulkConfig.StatsInfo = new StatsInfo
{
    StatsNumberUpdated = numberUpdated,
    StatsNumberDeleted = numberDeleted,
    StatsNumberInserted = totalNumber - numberUpdated - numberDeleted
};
StatsNumberInserted = totalNumber - numberUpdated - numberDeleted
```

I think, the number of inserted records cannot be calculated in this way, because of the additional statement `AND EXISTS (SELECT S.[Name] EXCEPT SELECT T.[Name])` after `WHEN MATCHED`.

**Comment by borisdj** [comment]
Will look into it.

**Comment by carltstein** [comment]
I am experiencing the same issue.

StatsInfo.StatsNumberInserted counts rows inserted AND rows where no changes were made.

I'm using:
Microsoft.EntityFrameworkCore.SqlServer 6.0.13
EFCore.BulkExtensions.SqlServer 6.6.5

p.s. Thanks @borisdj  for an awesome library that has shaved literally hours off of some of my sync operations

**Comment by palhal** [comment]
This also happens when I don't want to update existing rows:

```csharp
context.BulkInsertOrUpdate(items, new BulkConfig
{
    PropertiesToIncludeOnUpdate = new() { string.Empty }
});
```

Actual affected rows are 0, but since _StatsNumberUpdated_ is 0 (correct), _StatsNumberInserted_ is incorrectly set to _items.Count_.

**Comment by borisdj** [comment]
Fixed with latest v.

**Comment by acesteb** [comment]
@borisdj Using  latest version (7.1.5) with SQL Server, I am still seeing the _incorrect_ stats when using BulkInsertOrUpdate if nothing was updated.  (Going to build off of OP's example, the difference being BulkInsertOrUpdate vs BulkInsertOrUpdateOrDelete )

Given this initialization:

```
context.Students.BatchDelete();
context.Students.Add(new Student() { StudentId = 1, Name = "John Doe" });
context.SaveChanges();
```

and this config:

```
List<Student> students = new() { new Student() { StudentId = 1, Name = "John Doe" }};
BulkConfig bulkConfig = new() { CalculateStats = true };
context.BulkInsertOrUpdate(students, bulkConfig);
```

I would expect these results:

```
Deleted=0
Inserted=0
Updated=0
```

However, I am seeing these results instead: 
```
Deleted=0
Inserted=0
Updated=1
```

When I use the following config, I am seeing the expected results:
```
context.BulkInsertOrUpdate(students, new BulkConfig
{
    PropertiesToIncludeOnUpdate = new() { string.Empty },
    CalculateStats = true
});
```

However, this config is used as "Insert If Not Exists" functionality.  What I would like is for the update count to only increment if values changed.
